# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  www.josedudev.digital:
    site_hosts:
      - canonical: josedudev.test
    local_path: ../www.josedudev.digital # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@josedudev.digital
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
